=== jibrilsharafi/modbus-database/schemas/metadata_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Modbus Device Metadata",
    "type": "object",
    "properties": {
        "manufacturer": {
            "type": "string",
            "description": "The name of the manufacturer of the device."
        },
        "model": {
            "type": "string",
            "description": "The model identifier of the device."
        },
        "description": {
            "type": "string",
            "description": "A brief description of the device."
        },
        "version": {
            "type": "string",
            "description": "The version of the device or firmware."
        },
        "url": {
            "type": "string",
            "format": "uri",
            "description": "A URL to the device documentation or product page."
        },
        "tags": {
            "type": "object",
            "properties": {
                "industry": {
                    "type": "string",
                    "enum": [
                        "Energy",
                        "Manufacturing",
                        "Healthcare",
                        "Building Automation",
                        "Agriculture",
                        "Transportation",
                        "Water Management",
                        "Telecommunications",
                        "Oil and Gas",
                        "Smart Cities",
                        "Unknown"
                    ],
                    "description": "The industry in which the device is used."
                },
                "application": {
                    "type": "string",
                    "enum": [
                        "Energy Metering",
                        "Control",
                        "Monitoring",
                        "Automation",
                        "Data Collection",
                        "Diagnostics",
                        "Predictive Maintenance",
                        "Environmental Monitoring",
                        "Security",
                        "Process Optimization",
                        "Energy Generation",
                        "Energy Storage",
                        "Backup Power",
                        "Unknown"
                    ],
                    "description": "The specific application or functionality of the device."
                }
            },
            "required": [
                "industry",
                "application"
            ],
            "additionalProperties": false
        },
        "connection": {
            "type": "object",
            "properties": {
                "RTU": {
                    "type": "object",
                    "properties": {
                        "baudrate": {
                            "type": "integer",
                            "description": "The baud rate for the RTU connection."
                        },
                        "parity": {
                            "type": "string",
                            "enum": ["none", "even", "odd"],
                            "description": "The parity for the RTU connection."
                        },
                        "data_bits": {
                            "type": "integer",
                            "enum": [5, 6, 7, 8],
                            "description": "The number of data bits for the RTU connection."
                        },
                        "stop_bits": {
                            "type": "integer",
                            "enum": [1, 2],
                            "description": "The number of stop bits for the RTU connection."
                        },
                        "slave_id": {
                            "type": "integer",
                            "description": "The slave ID for the RTU connection."
                        },
                        "endianess": {
                            "type": "string",
                            "enum": ["big", "little"],
                            "description": "The endianess for the RTU connection."
                        }
                    },
                    "additionalProperties": false
                },
                "TCP": {
                    "type": "object",
                    "properties": {
                        "ip_address": {
                            "type": "string",
                            "format": "ipv4",
                            "description": "The IP address for the TCP connection."
                        },
                        "port": {
                            "type": "integer",
                            "description": "The port for the TCP connection."
                        },
                        "slave_id": {
                            "type": "integer",
                            "description": "The slave ID for the TCP connection."
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        }
    },
    "required": [
        "manufacturer",
        "model",
        "description",
        "version",
        "url",
        "tags"
    ],
    "additionalProperties": false
}

=== jibrilsharafi/modbus-database/modbus-tables/inepro/metering-pro380/latest/metadata.json
{
    "manufacturer": "inepro",
    "model": "metering-pro380",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/inepro-metering-pro380.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/secure/elite-103-elite-303-elite-307/latest/metadata.json
{
    "manufacturer": "secure",
    "model": "elite-103-elite-303-elite-307",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/secure-elite-103-elite-303-elite-307.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/siemens/sem3-single-phase/latest/metadata.json
{
    "manufacturer": "siemens",
    "model": "sem3-single-phase",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/siemens-sem3-single-phase.htm",
    "tags": {
        "industry": "Energy",
        "application": "Energy Metering"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/rayleigh/instruments-ri-f200/latest/metadata.json
{
    "manufacturer": "rayleigh",
    "model": "instruments-ri-f200",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/rayleigh-instruments-ri-f200.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/siemens/sentron-pac-4200/latest/metadata.json
{
    "manufacturer": "siemens",
    "model": "sentron-pac-4200",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/siemens-sentron-pac-4200.htm",
    "tags": {
        "industry": "Building Automation",
        "application": "Automation"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/northern/design-multicube-modbus/latest/metadata.json
{
    "manufacturer": "northern",
    "model": "design-multicube-modbus",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/northern-design-multicube-modbus.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/schneider/electric-sepam-40/latest/metadata.json
{
    "manufacturer": "schneider",
    "model": "electric-sepam-40",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/schneider-electric-sepam-40.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/lifasa/master-control-var/latest/metadata.json
{
    "manufacturer": "lifasa",
    "model": "master-control-var",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/lifasa-master-control-var.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}
