=== jibrilsharafi/modbus-database/schemas/metadata_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Modbus Device Metadata",
    "type": "object",
    "properties": {
        "manufacturer": {
            "type": "string",
            "description": "The name of the manufacturer of the device."
        },
        "model": {
            "type": "string",
            "description": "The model identifier of the device."
        },
        "description": {
            "type": "string",
            "description": "A brief description of the device."
        },
        "version": {
            "type": "string",
            "description": "The version of the device or firmware."
        },
        "url": {
            "type": "string",
            "format": "uri",
            "description": "A URL to the device documentation or product page."
        },
        "tags": {
            "type": "object",
            "properties": {
                "industry": {
                    "type": "string",
                    "enum": [
                        "Energy",
                        "Manufacturing",
                        "Healthcare",
                        "Building Automation",
                        "Agriculture",
                        "Transportation",
                        "Water Management",
                        "Telecommunications",
                        "Oil and Gas",
                        "Smart Cities",
                        "Unknown"
                    ],
                    "description": "The industry in which the device is used."
                },
                "application": {
                    "type": "string",
                    "enum": [
                        "Energy Metering",
                        "Control",
                        "Monitoring",
                        "Automation",
                        "Data Collection",
                        "Diagnostics",
                        "Predictive Maintenance",
                        "Environmental Monitoring",
                        "Security",
                        "Process Optimization",
                        "Energy Generation",
                        "Energy Storage",
                        "Backup Power",
                        "Unknown"
                    ],
                    "description": "The specific application or functionality of the device."
                }
            },
            "required": [
                "industry",
                "application"
            ],
            "additionalProperties": false
        },
        "connection": {
            "type": "object",
            "properties": {
                "RTU": {
                    "type": "object",
                    "properties": {
                        "baudrate": {
                            "type": "integer",
                            "description": "The baud rate for the RTU connection."
                        },
                        "parity": {
                            "type": "string",
                            "enum": ["none", "even", "odd"],
                            "description": "The parity for the RTU connection."
                        },
                        "data_bits": {
                            "type": "integer",
                            "enum": [5, 6, 7, 8],
                            "description": "The number of data bits for the RTU connection."
                        },
                        "stop_bits": {
                            "type": "integer",
                            "enum": [1, 2],
                            "description": "The number of stop bits for the RTU connection."
                        },
                        "slave_id": {
                            "type": "integer",
                            "description": "The slave ID for the RTU connection."
                        },
                        "endianess": {
                            "type": "string",
                            "enum": ["big", "little"],
                            "description": "The endianess for the RTU connection."
                        }
                    },
                    "additionalProperties": false
                },
                "TCP": {
                    "type": "object",
                    "properties": {
                        "ip_address": {
                            "type": "string",
                            "format": "ipv4",
                            "description": "The IP address for the TCP connection."
                        },
                        "port": {
                            "type": "integer",
                            "description": "The port for the TCP connection."
                        },
                        "slave_id": {
                            "type": "integer",
                            "description": "The slave ID for the TCP connection."
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        }
    },
    "required": [
        "manufacturer",
        "model",
        "description",
        "version",
        "url",
        "tags"
    ],
    "additionalProperties": false
}

=== jibrilsharafi/modbus-database/modbus-tables/smartprocess/smartrail-x835/latest/metadata.json
{
    "manufacturer": "smartprocess",
    "model": "smartrail-x835",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/smartprocess-smartrail-x835.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/lovato/electric-rgk800/latest/metadata.json
{
    "manufacturer": "lovato",
    "model": "electric-rgk800",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/lovato-electric-rgk800.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/solarx/power-hybrid-x1-hybrid-x3-x1ac/latest/metadata.json
{
    "manufacturer": "solarx",
    "model": "power-hybrid-x1-hybrid-x3-x1ac",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/solarx-power-hybrid-x1-hybrid-x3-x1ac.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/kael/multiser-01-multiser-11-multiser-13/latest/metadata.json
{
    "manufacturer": "kael",
    "model": "multiser-01-multiser-11-multiser-13",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/kael-multiser-01-multiser-11-multiser-13.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/schneider/electric-pm5500/latest/metadata.json
{
    "manufacturer": "schneider",
    "model": "electric-pm5500",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/schneider-electric-pm5500.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/kael/varkombi-18-pc-tft/latest/metadata.json
{
    "manufacturer": "kael",
    "model": "varkombi-18-pc-tft",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/kael-varkombi-18-pc-tft.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/schneider/electric-em1000-em1100-em1200/latest/metadata.json
{
    "manufacturer": "schneider",
    "model": "electric-em1000-em1100-em1200",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/schneider-electric-em1000-em1100-em1200.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/jiangsu/sfere-electric-sfere-720/latest/metadata.json
{
    "manufacturer": "jiangsu",
    "model": "sfere-electric-sfere-720",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/jiangsu-sfere-electric-sfere-720.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}
