=== jibrilsharafi/modbus-database/schemas/metadata_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Modbus Device Metadata",
    "type": "object",
    "properties": {
        "manufacturer": {
            "type": "string",
            "description": "The name of the manufacturer of the device."
        },
        "model": {
            "type": "string",
            "description": "The model identifier of the device."
        },
        "description": {
            "type": "string",
            "description": "A brief description of the device."
        },
        "version": {
            "type": "string",
            "description": "The version of the device or firmware."
        },
        "url": {
            "type": "string",
            "format": "uri",
            "description": "A URL to the device documentation or product page."
        },
        "tags": {
            "type": "object",
            "properties": {
                "industry": {
                    "type": "string",
                    "enum": [
                        "Energy",
                        "Manufacturing",
                        "Healthcare",
                        "Building Automation",
                        "Agriculture",
                        "Transportation",
                        "Water Management",
                        "Telecommunications",
                        "Oil and Gas",
                        "Smart Cities",
                        "Unknown"
                    ],
                    "description": "The industry in which the device is used."
                },
                "application": {
                    "type": "string",
                    "enum": [
                        "Energy Metering",
                        "Control",
                        "Monitoring",
                        "Automation",
                        "Data Collection",
                        "Diagnostics",
                        "Predictive Maintenance",
                        "Environmental Monitoring",
                        "Security",
                        "Process Optimization",
                        "Energy Generation",
                        "Energy Storage",
                        "Backup Power",
                        "Unknown"
                    ],
                    "description": "The specific application or functionality of the device."
                }
            },
            "required": [
                "industry",
                "application"
            ],
            "additionalProperties": false
        },
        "connection": {
            "type": "object",
            "properties": {
                "RTU": {
                    "type": "object",
                    "properties": {
                        "baudrate": {
                            "type": "integer",
                            "description": "The baud rate for the RTU connection."
                        },
                        "parity": {
                            "type": "string",
                            "enum": ["none", "even", "odd"],
                            "description": "The parity for the RTU connection."
                        },
                        "data_bits": {
                            "type": "integer",
                            "enum": [5, 6, 7, 8],
                            "description": "The number of data bits for the RTU connection."
                        },
                        "stop_bits": {
                            "type": "integer",
                            "enum": [1, 2],
                            "description": "The number of stop bits for the RTU connection."
                        },
                        "slave_id": {
                            "type": "integer",
                            "description": "The slave ID for the RTU connection."
                        },
                        "endianess": {
                            "type": "string",
                            "enum": ["big", "little"],
                            "description": "The endianess for the RTU connection."
                        }
                    },
                    "additionalProperties": false
                },
                "TCP": {
                    "type": "object",
                    "properties": {
                        "ip_address": {
                            "type": "string",
                            "format": "ipv4",
                            "description": "The IP address for the TCP connection."
                        },
                        "port": {
                            "type": "integer",
                            "description": "The port for the TCP connection."
                        },
                        "slave_id": {
                            "type": "integer",
                            "description": "The slave ID for the TCP connection."
                        }
                    },
                    "additionalProperties": false
                }
            },
            "additionalProperties": false
        }
    },
    "required": [
        "manufacturer",
        "model",
        "description",
        "version",
        "url",
        "tags"
    ],
    "additionalProperties": false
}

=== jibrilsharafi/modbus-database/modbus-tables/siemens/sem3-three-phase/latest/metadata.json
{
    "manufacturer": "siemens",
    "model": "sem3-three-phase",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/siemens-sem3-three-phase.htm",
    "tags": {
        "industry": "Energy",
        "application": "Energy Metering"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/electro/industries-shark-250/latest/metadata.json
{
    "manufacturer": "electro",
    "model": "industries-shark-250",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/electro-industries-shark-250.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/socomec/netys-pr-netys-rt-itys/latest/metadata.json
{
    "manufacturer": "socomec",
    "model": "netys-pr-netys-rt-itys",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/socomec-netys-pr-netys-rt-itys.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/fronius/power-meter-210-211/latest/metadata.json
{
    "manufacturer": "fronius",
    "model": "power-meter-210-211",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/fronius-power-meter-210-211.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/lifasa/master-control-var-fast/latest/metadata.json
{
    "manufacturer": "lifasa",
    "model": "master-control-var-fast",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/lifasa-master-control-var-fast.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/hager/ecn-ecp-ect-ecm-ecr-eca/latest/metadata.json
{
    "manufacturer": "hager",
    "model": "ecn-ecp-ect-ecm-ecr-eca",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/hager-ecn-ecp-ect-ecm-ecr-eca.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/power/one-inverter-pvi-aurora-central/latest/metadata.json
{
    "manufacturer": "power",
    "model": "one-inverter-pvi-aurora-central",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/power-one-inverter-pvi-aurora-central.htm",
    "tags": {
        "industry": "Unknown",
        "application": "Unknown"
    }
}

=== jibrilsharafi/modbus-database/modbus-tables/huawei/smartlogger/latest/metadata.json
{
    "manufacturer": "huawei",
    "model": "smartlogger",
    "description": "",
    "version": "",
    "url": "https://www.aggsoft.com/serial-data-logger/tutorials/modbus-data-logging/huawei-smartlogger.htm",
    "tags": {
        "industry": "Energy",
        "application": "Energy Generation"
    }
}
